version: "3.7"

services:
  mongo:
    image: mongo
    container_name: mongo-anime-notify
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
  api:
    build: .
    container_name: anime-notify-api
    ports:
      - 3000:3000
    volumes:
      - .:/usr/app